#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export API_ENDPOINT="${APP_URL}/api"
export CLIENT_ENDPOINT="${APP_URL}"

( cd /app/www/apps/server && s6-setuidgid abc node /app/www/apps/server/build/index.js --migrate )

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8080" \
        cd /app/www/apps/server s6-setuidgid abc node /app/www/apps/server/build/index.js
