#!/usr/bin/with-contenv bash
# shellcheck shell=bash

VAR_PATH="/app/www/apps/client/build"

cp "$VAR_PATH/variables-template.js" "$VAR_PATH/variables.js"

export API_ENDPOINT="${APP_URL}/api"

if [[ -n "$API_ENDPOINT" ]]; then
    echo "Setting API Endpoint to '$API_ENDPOINT'"
    sed -i "s;__API_ENDPOINT__;$API_ENDPOINT;g" "$VAR_PATH/variables.js"
else
    echo "API_ENDPOINT is not defined, web app won't work"
    exit 1
fi

HOME="/app"
